### ISSUE TITLE
Could not find module 'CocoaLumberjack' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by GlennBrann** [CocoaLumberjack/CocoaLumberjack#1263]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 CocoaLumberjack Version | 2.7.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 13.1

### Issue Description and Steps

When trying to build my project on my M1 chip mac, I get the following error 
```
could not find module 'CocoaLumberjack' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/username/Library/Developer/Xcode/DerivedData/PROJECT_REF/Build/Products/Debug-iphonesimulator/CocoaLumberjack/CocoaLumberjack.framework/Modules/CocoaLumberjack.swiftmodule
```

Any ideas how to fix this issue?

**Comment by bufrr** [comment]
same probloem here M1 mac when build x86 ios simulator

**Comment by ffried** [comment]
I think this should be resolved on `master`. Can you please give this a try?

**Comment by GlennBrann** [comment]
> I think this should be resolved on `master`. Can you please give this a try?

Hi Florian, I tried adding this to my Podfile, doing an pod deintegrate, clean and install again. I also tried cleaning derived data.
```
pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'master'
```
I still get the following
![Screen Shot 2021-12-10 at 1 45 33 PM](https://user-images.githubusercontent.com/5156285/145625923-bf3b4aa0-ac44-40a8-8fd8-38213932b83f.png)

**Comment by ffried** [comment]
Weird. I thought we changed something there. Will have to take another look at this.
I think it CocoaPods might be involved here. We're using CocoaLumberjack via SPM (v3.7.2) and it builds fine against the simulator on our M1 Macs.

Meanwhile, can you try if something like [this answer](https://stackoverflow.com/a/66420027) helps?

**Comment by sushichop** [comment]
In addition, can you try to use the latest cocoapods(1.11.2)?
Just FYI: I was able to build CocoaLumberjack 3.7.2 using cocoapods 1.11.2, though with Intel Mac...

**Comment by via-guy** [comment]
I'm having this issue myself.

**Comment by romankozakskelia** [comment]
I get this issue on m2

**Comment by via-guy** [comment]
@ffried can we please reopen this issue?

**Comment by ffried** [comment]
@via-guy Since I cannot reproduce the issue (neither on M1, nor on M2 nor on Intel), I'd like to request a small reproduction project for re-opening this. Otherwise it'll simply be closed again by stale-bot since I don't really have something to go on here.

**Comment by romankozakskelia** [comment]
@via-guy I worked around it by running Xcode with Rosetta (right click Xcode -> Get info -> check rosetta)

**Comment by masture** [comment]
@via-guy , I am facing same issue after updating Xcode to 14.3 (14E222b) on macOS: 13.3 (22E252).
I am using cocoapod 1.11.2 and CocoaLumberjack/Swift (3.8.0) on Intel MBP. 
Note: This wasn't the issue with Xcode 14.2. 
Does update to Swift 5.8 a reason?

**Comment by via-guy** [comment]
@masture no, this happened before Xcode 14.3 for me. It was happening when I was trying to build a Flutter native module. I'll need to try and reproduce when I get a chance.

**Comment by nesimtunc** [comment]
Still no solution?
