### ISSUE TITLE
Xcode 8 Beta support for Swift

### ISSUE THREAD

**Issue by lvandal** [CocoaLumberjack/CocoaLumberjack#763]
Code won't compile for the last couple betas.

> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by bpoplauschi** [comment]
Should be fixed by #747

**Comment by lvandal** [comment]
No. This still doesn't work. Try using Carthage with Xcode 8 beta being the selected version and you'll get this:

`** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/lucvandal/Repositories/Screens 4/screens-4-ios/Vendor/Carthage/Checkouts/CocoaLumberjack/Framework/Lumberjack.xcworkspace -scheme CocoaLumberjackSwift -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)`
